# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_auto_20161002_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_head',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
