# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_article_sub_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('date_time', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
