# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
